# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2020-12-16 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_auto_20201213_0559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custumer',
            name='class_list',
            field=models.ManyToManyField(blank=True, null=True, to='sales.Classlist', verbose_name='已报班级'),
        ),
        migrations.AlterField(
            model_name='custumer',
            name='name',
            field=models.CharField(help_text='学员报名后可改为真实姓名', max_length=32, verbose_name='姓名'),
        ),
    ]
