# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-01-02 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0008_auto_20210103_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='is_menu',
            field=models.BooleanField(default=False),
        ),
    ]
