# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2021-01-03 15:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_permission_is_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=16)),
            ],
        ),
        migrations.AddField(
            model_name='permission',
            name='menus',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='sales.Menu'),
        ),
    ]
